### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by victorlapin** [BattletechModders/PanicSystem#13]
Hey there! 

Is this mod no longer vanilla compatible? The game hangs up as soon as one of my pilots takes some damage, with or without several other mods installed. Is this RT only now? Reverting back to gnivler's latest version (I believe it was 3.7.8) fixes the gameplay. I have no CAC installed, btw, as it's marked as optional dependency.

**Comment by fmnatic** [comment]
@victorlapin  
The release has separate NO CAC / CAC build. NO CAC should have the same compatibility as gnivler's last version
Can you switch on the log in mod.json and provide the log , as well as vanilla logs.
    "Debug":  true.

**Comment by victorlapin** [comment]
Sure, I'll give it a try. I can see only CAC version in the release section, though

**Comment by fmnatic** [comment]
Added the NO_CAC build here. Please report any problems with it.
https://github.com/BattletechModders/PanicSystem/releases/tag/REL_4.2.0

**Comment by victorlapin** [comment]
Looks all good so far!
