### ISSUE TITLE
Does not read CanEject statistic 

### ISSUE THREAD

**Issue by IceRaptor** [BattletechModders/PanicSystem#14]
The base game provides the _CanEject_ statistic, a boolean that determines if a pilot can eject. PanicSystem should read this as well, to allow mod authors to mark certain units as unable or unwilling to eject.

**Comment by fmnatic** [comment]
Added two settings. Setting both to true, blocks most ejections on RT 1.7.7 HF5
#rogueticket-765

Both default to false

```
    /*Block Ejection for Pilots with CanEject Stat set to false*/
    "ObeyPilotCanEjectStat": true,

    /*Block Ejection for Pilots with pilot_cannot_eject Tag*/
    "ObeyPilotCannotEjectTag": false
```
