### ISSUE TITLE
The compiled version in Releases is CAC ONLY and many vanilla players are lost

### ISSUE THREAD

**Issue by Kornstalx** [BattletechModders/PanicSystem#18]
That dependency needs to be removed as it is stumbling players that do not know how to compile their own versions. The NO_CAC version of PanicSystem does not exist pre-compiled, or I can't find it if it does.

**Comment by fmnatic** [comment]
All the releases i've made on the Rt discord have the NO_CAC version as well. Let me know where you'd like the release.

**Comment by fmnatic** [comment]
Added the NO_CAC build here. Please report any problems with it.
https://github.com/BattletechModders/PanicSystem/releases/tag/REL_4.2.0
